"""Writes (or checks) zig/kernels/cuda/fn_qmmf_ld.cu: fn_qmmf.cu's FP8G lane matmul with one change, an output row
stride `ldo` (the INT4-AutoRound projections write their block-FP8 columns straight into the wider projection row
instead of a scratch copied into place). Every instruction that computes a value is fn_qmmf.cu's; only the store
address of the bf16/fp32 output changes (row * ldo + col instead of row * N + col), so the bytes written are the
same values (cuda_fp8.zig matmulLd, checked by `tensorfold fp8-check`).

Usage: python3 tools/zig/flashnext_qmmf_ld.py [--check]
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "zig/kernels/cuda/fn_qmmf.cu"
OUT = ROOT / "zig/kernels/cuda/fn_qmmf_ld.cu"

FOOTER = """
// Block FP8 (FP8G) with an output row stride, bf16 out: row tiles 16, 32, 64 with one K slice or 2-8 in a cluster,
// and the fused prompt form (fn_qmmf.cu's instantiations, bf16 ones only).
#define TF_QMMF_LD(BM, CLUSTER, FUSE) template __global__ void tf_fn_qmmf_ld::qmmf_kernel<3, BM, 64, 1, 4, 4, false, \\
    CLUSTER, FUSE>(const __nv_bfloat16*, const unsigned char*, const uint8_t*, float, void*, float*, int, int, int, \\
    int, int, int, int, int);
TF_QMMF_LD(16, false, false)
TF_QMMF_LD(32, false, false)
TF_QMMF_LD(64, false, false)
TF_QMMF_LD(16, true, false)
TF_QMMF_LD(32, true, false)
TF_QMMF_LD(64, true, false)
TF_QMMF_LD(64, false, true)
"""


def edit(text: str) -> str:
    def once(s: str, old: str, new: str) -> str:
        if s.count(old) != 1:
            raise SystemExit(f"fn_qmmf.cu changed: {old!r} found {s.count(old)} times")
        return s.replace(old, new)

    body = text[: text.index("// Block FP8 (FP8G, an fp32 scale per 64 inputs")]
    body = once(body, "namespace tf_fn_qmmf {", "namespace tf_fn_qmmf_ld {")
    body = once(body, "} // namespace tf_fn_qmmf\n", "} // namespace tf_fn_qmmf_ld\n")
    body = once(body, "int npad, int ldx,\n        int group) {", "int npad, int ldx,\n        int group, int ldo) {")
    body = once(body, "reinterpret_cast<float*>(out) + static_cast<size_t>(row) * N + col;",
                "reinterpret_cast<float*>(out) + static_cast<size_t>(row) * ldo + col;")
    body = once(body, "reinterpret_cast<__nv_bfloat16*>(out) + static_cast<size_t>(row) * N + col;",
                "reinterpret_cast<__nv_bfloat16*>(out) + static_cast<size_t>(row) * ldo + col;")
    head = ("// Generated by tools/zig/flashnext_qmmf_ld.py from fn_qmmf.cu (TensorFold's cuda/nvfp4/qmmf.cu, by Ash Hart):\n"
            "// the same kernel with an output row stride `ldo`; do not edit by hand.\n")
    return head + body + FOOTER


def main() -> int:
    want = edit(SRC.read_text())
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == want
        print(("OK " if ok else "STALE ") + str(OUT.relative_to(ROOT)))
        return 0 if ok else 1
    OUT.write_text(want)
    print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
